name: Linux Installation Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "ubuntu"
          - "fedora"
          - "archlinux"
          - "opensuse/leap"
    container: '${{ matrix.os }}'
    steps:
      - name: Print Distro Info
        run: cat /etc/os-release
        shell: bash
      
      - name: Update System and Git
        run: |
          case ${{ matrix.os }} in
            ubuntu)
              apt-get update && apt-get upgrade -y && apt-get install -y git
              ;;
            fedora)
              dnf update -y && dnf install -y git
              ;;
            archlinux)
              pacman -Syu --noconfirm && pacman -S --noconfirm git
              ;;
            opensuse/leap)
              zypper refresh && zypper update -y && zypper install -y git
              ;;
          esac
        shell: bash

      - uses: actions/checkout@v4

      - name: Install ZVM
        run: cat install.sh | bash
